---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cc-pvc-azurefile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: cc-pv-azurefile
  storageClassName: cc-azurefile-csi
