---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cc-pvc-azurefile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: cc-azurefile-csi
