---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cc-managed-premium-csi
provisioner: cc.disk.csi.azure.com
parameters:
  skuName: Premium_LRS
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
