---
apiVersion: v1
kind: Pod
metadata:
  name: many-layers
spec:
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
  runtimeClassName: kata-cc
  containers:
    - name: azure-vote-front
      image: "mcr.microsoft.com/azuredocs/azure-vote-front:v1"
      command:
        - sh
        - "-c"
        - while true; do echo hello; sleep 10; done
    - name: mariner-cli
      image: "mcr.microsoft.com/azure-cli:2.58.0-cbl-mariner2.0-amd64"
      command:
        - sh
        - "-c"
        - while true; do az --help; sleep 15; done
    - name: nginx
      image: "mcr.microsoft.com/cbl-mariner/base/nginx:1.22.1-9-cm2.0.20230904-amd64"
      command:
        - sh
        - "-c"
        - while true; do echo nginx; sleep 10; done
