apiVersion: v1
entries:
  azurefile-csi-driver:
  - apiVersion: v1
    appVersion: v1.30.1
    created: "2024-04-12T08:52:54.325890808Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: d56f16830759ed0cfa8aabff89547b6ab3f2ec3d3371d012ac3e7c9642311da3
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.30.1/azurefile-csi-driver-v1.30.1.tgz
    version: v1.30.1
  - apiVersion: v1
    appVersion: v1.30.0
    created: "2024-04-12T08:52:54.324816098Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 026831beb77a3d28a55b5fe7e0badbaf17c22f5b5a16a9b2ffc0a06bebc4e218
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.30.0/azurefile-csi-driver-v1.30.0.tgz
    version: v1.30.0
  - apiVersion: v1
    appVersion: v1.29.4
    created: "2024-04-12T08:52:54.323278902Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 820020b2a8c919c8dbd28b4a92767e2feeb4d282ac6003b5781fc6abcbc5e0c7
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.4/azurefile-csi-driver-v1.29.4.tgz
    version: v1.29.4
  - apiVersion: v1
    appVersion: v1.29.2
    created: "2024-04-12T08:52:54.321835834Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: dcf667e5fd62b4787ee382cd638d2d802bff939d919bc2fdbac359beb614d335
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.2/azurefile-csi-driver-v1.29.2.tgz
    version: v1.29.2
  - apiVersion: v1
    appVersion: v1.29.1
    created: "2024-04-12T08:52:54.320753837Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: a7e3bc8bb3e17153f35387f2040210d72ac5545a9446b0a37660273b5635e11d
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.1/azurefile-csi-driver-v1.29.1.tgz
    version: v1.29.1
  - apiVersion: v1
    appVersion: v1.29.0
    created: "2024-04-12T08:52:54.319645715Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 2da242b471ff0eaf6ea3f1a9d2c1f6aaa1b78c8cbb4e850bbefb336e043b8098
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.0/azurefile-csi-driver-v1.29.0.tgz
    version: v1.29.0
  - apiVersion: v1
    appVersion: v1.28.9
    created: "2024-04-12T08:52:54.318534716Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 9ccf3d29c7f690c9ef5404a14b0b3995d53a14790cc54934b1299e40cd30621c
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.28.9/azurefile-csi-driver-v1.28.9.tgz
    version: v1.28.9
  - apiVersion: v1
    appVersion: v1.28.7
    created: "2024-04-12T08:52:54.316463423Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: b662264a632d651132b4069fcdd5f859e3d45559d9071cb8a482396ebdef11a6
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.28.7/azurefile-csi-driver-v1.28.7.tgz
    version: v1.28.7
  - apiVersion: v1
    appVersion: v1.28.6
    created: "2024-04-12T08:52:54.315362334Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 6e71c5e9429b99533982895c17ad39159c078154e14a4779a5f12d3f9aca992f
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.28.6/azurefile-csi-driver-v1.28.6.tgz
    version: v1.28.6
  - apiVersion: v1
    appVersion: v1.28.3
    created: "2024-04-12T08:52:54.314242054Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 58e138f7a8f2a925c56ca26dc220cab2dc723691c23fd011b457624d11889395
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.28.3/azurefile-csi-driver-v1.28.3.tgz
    version: v1.28.3
  - apiVersion: v1
    appVersion: v1.28.2
    created: "2024-04-12T08:52:54.313130247Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 426fad83a42035af15af775bd37c73309ef0cfe22686babb0668be71da70a66e
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.28.2/azurefile-csi-driver-v1.28.2.tgz
    version: v1.28.2
  - apiVersion: v1
    appVersion: v1.27.3
    created: "2024-04-12T08:52:54.312040741Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 330d2b11f93e2b10d36f64ed6de528b61351ca794dd9b2c3690c6f6790008732
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.27.3/azurefile-csi-driver-v1.27.3.tgz
    version: v1.27.3
  - apiVersion: v1
    appVersion: v1.27.2
    created: "2024-04-12T08:52:54.310800878Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: ab72e0e5f360a38f63e87147ef47ef213016578e8ba64fbb32ecaf2aad7ffdf3
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.27.2/azurefile-csi-driver-v1.27.2.tgz
    version: v1.27.2
  - apiVersion: v1
    appVersion: v1.26.10
    created: "2024-04-12T08:52:54.306808083Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 80d2fccdab497044587f8a3299cc761cdf364c2d2d0b4f4cb0ab8197021dc218
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.10/azurefile-csi-driver-v1.26.10.tgz
    version: v1.26.10
  - apiVersion: v1
    appVersion: v1.26.6
    created: "2024-04-12T08:52:54.308855279Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 3c20488343b47ed618e8c809f6fcdd83f22e00a4d07c78ca097573cafd7075a9
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.6/azurefile-csi-driver-v1.26.6.tgz
    version: v1.26.6
  - apiVersion: v1
    appVersion: v1.26.5
    created: "2024-04-12T08:52:54.307823064Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 62ac6ab864264ee1e2fb86e8093c8e8263c2c0d3bafff60704c31fd72e40c604
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.5/azurefile-csi-driver-v1.26.5.tgz
    version: v1.26.5
  - apiVersion: v1
    appVersion: v1.25.1
    created: "2024-04-12T08:52:54.30578252Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 2bf374cc321c5bc8e76e06cd5df85ce7d7d14574397e7e7f7173077393f554c4
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.25.1/azurefile-csi-driver-v1.25.1.tgz
    version: v1.25.1
  - apiVersion: v1
    appVersion: v1.24.11
    created: "2024-04-12T08:52:54.301789311Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 501e27a634966a4ae5528025577e926745d896ffa2c253dc69c13623b84254d2
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.24.11/azurefile-csi-driver-v1.24.11.tgz
    version: v1.24.11
  - apiVersion: v1
    appVersion: v1.24.7
    created: "2024-04-12T08:52:54.304751383Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 9e5b3f32ad823f845e5a09af230f7a934851943d6afcab3bd545233838680d83
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.24.7/azurefile-csi-driver-v1.24.7.tgz
    version: v1.24.7
  - apiVersion: v1
    appVersion: v1.24.6
    created: "2024-04-12T08:52:54.302892009Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: dbd0a6e27a09fec002c57029bd6e34a6ee92d1c10e708935e3f2150069a35ee5
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.24.6/azurefile-csi-driver-v1.24.6.tgz
    version: v1.24.6
  - apiVersion: v1
    appVersion: v1.23.0
    created: "2024-04-12T08:52:54.300755388Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 5fcb33617d16e90df1e7041b0df02e5bd92595e86381db30d356b0b2e3500bc4
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.23.0/azurefile-csi-driver-v1.23.0.tgz
    version: v1.23.0
  - apiVersion: v1
    appVersion: v1.22.0
    created: "2024-04-12T08:52:54.299760769Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 253d87a8b876dbdd55870a7fee88547393179d03f193661125f5a0b63411f922
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.22.0/azurefile-csi-driver-v1.22.0.tgz
    version: v1.22.0
  - apiVersion: v1
    appVersion: v1.21.0
    created: "2024-04-12T08:52:54.29867194Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: d45bf3455ebadc9cc5afaf9da66aa1ea1d4b719cfdff5af661f93bb26c01a504
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.21.0/azurefile-csi-driver-v1.21.0.tgz
    version: v1.21.0
  - apiVersion: v1
    appVersion: v1.20.0
    created: "2024-04-12T08:52:54.297077915Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 7cc43d57a79137aea5414fb51a9bbd77bb679b29ee49c06865c1a5b9ba60be99
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.20.0/azurefile-csi-driver-v1.20.0.tgz
    version: v1.20.0
  - apiVersion: v1
    appVersion: v1.19.0
    created: "2024-04-12T08:52:54.295834718Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 18f6efbed424efd661fde43be2e5a48a5012a46a7938c33b36963cbd9875a5af
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.19.0/azurefile-csi-driver-v1.19.0.tgz
    version: v1.19.0
  - apiVersion: v1
    appVersion: v1.18.0
    created: "2024-04-12T08:52:54.29485121Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 696ca23d9ee517f71ef5e852955c8d0f1017c331c025426c6fcbe7a06d006c66
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.18.0/azurefile-csi-driver-v1.18.0.tgz
    version: v1.18.0
  - apiVersion: v1
    appVersion: v1.17.0
    created: "2024-04-12T08:52:54.293890702Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 5632f61265a3b78dce3e2b15e07cc9b14a7f54a778878c02ca2d9fe69ca0344e
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.17.0/azurefile-csi-driver-v1.17.0.tgz
    version: v1.17.0
  - apiVersion: v1
    appVersion: v1.16.0
    created: "2024-04-12T08:52:54.292929238Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: a7a2d57e8eca7dc06c8b2cffb9bccb857753eb110b8e70760b3e04f4e6a87552
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.16.0/azurefile-csi-driver-v1.16.0.tgz
    version: v1.16.0
  - apiVersion: v1
    appVersion: v1.15.0
    created: "2024-04-12T08:52:54.291994633Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: c1a31dadce233a90c19dce70f6cc92ba2e20bbaa1b1883baea72381d09303118
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.15.0/azurefile-csi-driver-v1.15.0.tgz
    version: v1.15.0
  - apiVersion: v1
    appVersion: v1.14.0
    created: "2024-04-12T08:52:54.290924276Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 0c9ad4afa5ebfdb2851ad93eb16a0382d61448714b7556899360730a2fdf463a
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.14.0/azurefile-csi-driver-v1.14.0.tgz
    version: v1.14.0
  - apiVersion: v1
    appVersion: v1.13.0
    created: "2024-04-12T08:52:54.288666892Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 214042b029d858b50a0f8bba33a7aa2b41d1b67bce16f957ca183ae7438dac3f
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.13.0/azurefile-csi-driver-v1.13.0.tgz
    version: v1.13.0
  - apiVersion: v1
    appVersion: v1.12.0
    created: "2024-04-12T08:52:54.287589126Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: fbd63929671066a26df898d32282a6e79c39499a39c71761c546d069459d847d
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.12.0/azurefile-csi-driver-v1.12.0.tgz
    version: v1.12.0
  - apiVersion: v1
    appVersion: v1.11.0
    created: "2024-04-12T08:52:54.28654624Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 76bd438f8391d08235b09fbca859f25a9fcf8e018fd1e7e33444ca9ea946ce4b
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.11.0/azurefile-csi-driver-v1.11.0.tgz
    version: v1.11.0
  - apiVersion: v1
    appVersion: v1.10.0
    created: "2024-04-12T08:52:54.285608117Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 845a9de8b571b255d05ae9c643d9b90a57fe6507ff3fb735c88b41f99f6f28dc
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.10.0/azurefile-csi-driver-v1.10.0.tgz
    version: v1.10.0
  - apiVersion: v1
    appVersion: latest
    created: "2024-04-12T08:52:54.284640648Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 4777d586deed224d5ee6c1b5f4981dc914c4911ba9a78034f4979c704249d8cd
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/latest/azurefile-csi-driver-v0.0.0.tgz
    version: v0.0.0
generated: "2024-04-12T08:52:54.28333827Z"
